### ISSUE TITLE
Please include some documentation about how cohesion is calculated

### ISSUE THREAD

**Issue by sureshvv** [mschwager/cohesion#7]
and why it is useful

**Comment by mschwager** [comment]
Hey @sureshvv, thanks for bringing this to my attention!

The introduction does a pretty good job of explaining why measuring cohesion can be useful: https://github.com/mschwager/cohesion#cohesion

But, I agree, there's not much insight into how it gets calculated. One may be able to reverse engineer it from the example in the README, but that's not very convenient. Would an explanation make more sense to you, or something like pseudo-code? E.g.

> A class's cohesion is calculated by taking the average of all function's "boundedness" for all functions in a class, where boundedness is the percentage of bound variables (e.g. `self`) used by a given function against the total amount of bound variables in a class.

Or in pseudo-code:

> sum ( function.bound_variable_count / class.bound_variable_count for function in class ) / class.function_count

**Comment by sureshvv** [comment]
Thank you for this explanation. I am sure it will help when added to the documentation. Examples of good and bad cohesion will seal the deal :)
